name: Build Seeed Xiao ESP32c3 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          .pio
        key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PlatformIO Core
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pip install esptool

    - name: Build firmware with PlatformIO
      run: pio run
      
    - name: Merge ESP32-C3 binaries
      run: |
        esptool.py --chip esp32c3 merge_bin \
          -o .pio/build/seeed_xiao_esp32c3/merged-firmware.bin \
          --flash_mode dio \
          --flash_freq 40m \
          --flash_size 4MB \
          0x0000 .pio/build/seeed_xiao_esp32c3/bootloader.bin \
          0x8000 .pio/build/seeed_xiao_esp32c3/partitions.bin \
          0x10000 .pio/build/seeed_xiao_esp32c3/firmware.bin

    - name: Generate manifest
      run: |
        cat > dist/manifest.json << 'EOF'
        {
          "name": "Pauna ESP32-C3 Firmware",
          "version": "1.0.0",
          "new_install_prompt_erase": true,
          "new_install_improv_wait_time": 30,
          "builds": [
            {
              "chipFamily": "ESP32-C3",
              "improv": false,
              "parts": [
                { "path": "merged-firmware.bin", "offset": 0 }
              ]
            }
          ]
        }
        EOF
        cp .pio/build/seeed_xiao_esp32c3/merged-firmware.bin dist/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp-web-flash
        path: dist/

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist


